// Listas centralizadas de categorías de locales y tipos de profesionales.
// Úsalas en filtros y formularios para mantener todo consistente en un solo lugar.

export const PROFESSIONS = [
  "Médico",
  "Odontólogo",
  "Veterinario",
  "Psicólogo / Psicoterapeuta",
  "Fisioterapeuta",
  "Nutricionista / Dietista",
  "Optómetra",
  "Abogado",
  "Notario / Inspector",
  "Detective privado",
  "Profesor particular",
  "Traductor / Intérprete",
  "Coach / Capacitador",
  "Arquitecto",
  "Ingeniero civil / estructural",
  "Técnico electrónico / electricista",
  "Topógrafo",
  "Maestro de obra / Constructor",
  "Contador / Auditor",
  "Asesor financiero",
  "Consultor en logística / Supply Chain",
  "Consultor de e-commerce",
  "Agente de seguros",
  "Diseñador gráfico / UX",
  "Fotógrafo / Videógrafo",
  "Escritor / Copywriter",
  "Músico / Productor",
  "Actor / Artista escénico",
  "Desarrollador de software",
  "Especialista en ciberseguridad",
  "Community manager / Marketing digital",
  "Consultor de IA / Data",
  "Agente inmobiliario",
  "Consultor de RRHH",
  "Trabajador social / Gestor comunitario",
  "Guía turístico",
  "Transportador / Mensajero",
  // Genéricos heredados (búsquedas amplias)
  "Programador",
  "Otro",
];

export const LOCAL_CATEGORIES = [
  "Barbería",
  "Salón de belleza",
  "Cafetería",
  "Panadería",
  "Supermercado",
  "Minimercado / Tienda de barrio",
  "Droguería / Farmacia",
  "Restaurante",
  "Pizzería",
  "Heladería",
  "Frutería",
  "Carnicería",
  "Pescadería",
  "Verdulería / Granero",
  "Papelería",
  "Ferretería",
  "Miscelánea",
  "Librería",
  "Zapatería",
  "Ropa y accesorios / Boutique",
  "Joyería",
  "Relojería",
  "Óptica",
  "Peluquería canina / Pet shop",
  "Veterinaria",
  "Floristería",
  "Vivero / Plantas",
  "Lavandería",
  "Tintorería",
  "Sastrería / Modistería",
  "Zapatero / Reparación de calzado",
  "Cerrajería",
  "Taller mecánico",
  "Taller de motos",
  "Taller de bicicletas",
  "Vulcanizadora",
  "Lavadero de autos",
  "Concesionario de vehículos",
  "Estudio fotográfico",
  "Imprenta / Litografía",
  "Citofonía / Instalaciones eléctricas",
  "Depósito de materiales de construcción",
  "Vidriería",
  "Mueblería / Ebanistería",
  "Colchonería",
  "Electrodomésticos",
  "Tecnología y celulares",
  "Reparación de celulares",
  "Servicio técnico de electrodomésticos",
  "Juguetería",
  "Artículos deportivos",
  "Bicicletería",
  "Tienda naturista / Herboristería",
  "Spa / Centro de estética",
  "Centro de bronceado",
  "Tatuajes y piercings",
  "Gimnasio",
  "Estudio de yoga / pilates",
  "Escuela de danza",
  "Escuela de música",
  "Centro de idiomas",
  "Guardería / Jardín infantil",
  "Centro de cómputo / Café internet",
  "Sala de juegos / Arcade",
  "Billar",
  "Parrilla / Asadero",
  "Sanduichería",
  "Sushería",
  "Cevichería",
  "Fritanga / Comidas rápidas",
  "Jugos y batidos",
  "Chocolatería / Pastelería",
  "Dulcería / Confitería",
  "Tabaquería / Cigarrería",
  "Licorera",
  "Depósito de cerveza",
  "Billares y cantina",
  "Alquiler de disfraces",
  "Alquiler de herramientas",
  "Alquiler de equipos para eventos",
  "Agencia de viajes",
  "Agencia de seguros",
  "Centro de copiado y papelería",
  "Enmarcado y cuadros",
  "Artesanías y souvenirs",
  "Galería de arte",
  "Anticuario / Objetos de colección",
  "Segunda mano / Ropa usada",
  "Casa de empeño",
  "Cambio de divisas",
  "Corresponsal bancario",
  "Servicio de envíos / Mensajería",
  "Distribuidora de agua",
  "Distribuidora de gas",
  "Punto de recarga de minutos",
  "Agencia de lotería / Chance",
  "Funeraria / Servicios fúnebres",
  "Alquiler de ropa formal",
  "Peluquería barbería afro",
  "Centro de rehabilitación / Fisioterapia",
  "Sala de cine",
  "Teatro",
  "Bolos / Bowling",
  "Karting / Pista de karts",
  "Paintball / Airsoft",
  "Escape room",
  "Parque de trampolines",
  "Pista de patinaje",
  "Cancha de fútbol sintética",
  "Cancha de tenis / pádel",
  "Piscina pública / Club acuático",
  "Club de boxeo / artes marciales",
  "Campo de golf / Minigolf",
  "Peña / Bar con música en vivo",
  "Karaoke",
  "Discoteca / Rumbeadero",
  "Casino",
  "Sala de apuestas deportivas",
  "Hostal / Residencia",
  "Hotel boutique",
  "Motel",
  "Apartahotel",
  "Camping / Glamping",
  "Finca turística",
  "Lavado de ropa a domicilio",
  "Depósito de chatarra / Reciclaje",
  "Vivero de peces / Acuario",
  "Criadero de animales",
  "Consultorio médico / Clínica estética",
  "Centro de diagnóstico / Laboratorio clínico",
  "Centro de vacunación",
  "Óptica con examen visual",
  "Clínica odontológica",
  "Centro de nutrición y bienestar",
  "Estudio de grabación",
  "Estudio de podcast",
  "Coworking",
  "Sala de eventos / Salón de fiestas",
  "Alquiler de bodegas / Self storage",
  "Parking / Parqueadero",
  "Cancha de voleibol",
  "Cancha de pádel",
  "Estanquillo",
  "Cancha de baloncesto",
  "Cancha de béisbol / softbol",
  "Cancha de squash",
  "Campo de tiro / Polígono",
  "Pista de atletismo",
  "Skatepark",
  "Club de ciclismo",
  "Tienda de vinos / Vinoteca",
  "Cigarrería / Tabaquería fina",
  "Bar de cócteles / Coctelería",
  "Cervecería artesanal",
  "Café de especialidad",
  "Crepería",
  "Wafflería",
  "Bubble tea / Té asiático",
  "Arepería",
  "Tamales y empanadas",
  "Chorizería / Longanizería",
  "Asadero de pollos",
  "Marisquería",
  "Sopas y caldos",
  "Restaurante de comida árabe",
  "Restaurante de comida china",
  "Restaurante de comida italiana",
  "Restaurante vegetariano / vegano",
  "Restaurante de comida costeña",
  "Tienda de productos orgánicos",
  "Tienda de suplementos deportivos",
  "Tienda de productos naturales importados",
  "Bazar / Todo a mil",
  "Piñatería",
  "Cotillón / Artículos de fiesta",
  "Distribuidora de huevos",
  "Distribuidora de lácteos",
  "Distribuidora de abarrotes",
  "Distribuidora de licores",
  "Punto de venta de carbón / leña",
  "Cerería / Velas y artículos religiosos",
  "Librería religiosa / Artículos de fe",
  "Tienda esotérica / Botánica",
  "Estudio de tarot / Videncia",
  "Centro de meditación",
  "Estudio de fotografía de moda",
  "Agencia de publicidad local",
  "Agencia de diseño gráfico",
  "Centro de reparación de computadores",
  "Punto de venta de repuestos electrónicos",
  "Taller de joyería / Orfebrería",
  "Taller de relojería",
  "Taller de tapicería",
  "Taller de soldadura / Metalmecánica",
  "Taller de carpintería",
  "Taller de pintura automotriz",
  "Distribuidora de repuestos de motos",
  "Distribuidora de repuestos de carros",
  "Agencia de carga / Fletes",
  "Centro de estética canina",
  // Genéricos heredados (categorías amplias / búsquedas)
  "Tienda",
  "Bar",
  "Servicio",
  "Salud",
  "Educación",
  "Moda",
  "Tecnología",
  "Entretenimiento",
  "Otro",
];
